[project]
name = "pucp-web-mining-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faicons>=0.2.2",
    "fontawesome>=5.10.1.post1",
    "polars>=1.17.1",
    "shiny>=1.2.1",
]
